@startuml check_input

start
    if (input has length 5?) then (no)
        :error = "incorrect length";
    (yes) elseif (input is a word?) then (no)
        :error = "unrecognized word";
    (yes) elseif (input already guessed?) then (no)
        :error = "already guessed";
    else (yes)
        ' :error = none;
    endif
stop

@enduml
