@startuml rules

title Word Game Rules

start

:secretly pick a word;

repeat
    :draw board;
    :read input;
    :check input;
    if (input ok?) then (no)
        :print error;
    else
        :add guess to guesses;
    endif
repeat while (6 wrong guesses or 1 correct guess?) is (no) not (yes)

:print game result;

stop

@enduml
